<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <UserSecretsId>307a961c-e66c-4502-afee-17752a8db15d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeatherDashboard.Infrastructure\WeatherDashboard.Infrastructure.csproj" />
    <ProjectReference Include="..\WeatherDashboard.Domain\WeatherDashboard.Domain.csproj" />
  </ItemGroup>

</Project>
